### ISSUE TITLE
Checks into inn, setting set to false.

### ISSUE THREAD

**Issue by blackcatsnow** [bumbleshoot/automate-habitica#27]
**What is the bug?**
The script auto checks me into the inn several times a day even though the auto resume damage is set to false. I followed the instructions to change the settings but it did not resolve the issue. 

**Additional context**
There is always a quest invited or currently running when it happens, but again, the setting is set to false. 

**How often does this happen?**
Several times a day

**Script version**
29.32

**Script settings**
```
const AUTO_CRON = true; // true or false

const AUTO_ACCEPT_QUEST_INVITES = true;

const FORCE_START_QUESTS = true; // party leaders only
const FORCE_START_QUESTS_AFTER_HOURS = 24; // eg. if set to 1, quests will force start after 1h
const NOTIFY_MEMBERS_EXCLUDED_FROM_QUEST = true;

const AUTO_INVITE_GOLD_QUESTS = false;
const AUTO_INVITE_UNLOCKABLE_QUESTS = false;
const AUTO_INVITE_PET_QUESTS = false;
const AUTO_INVITE_HOURGLASS_QUESTS = false;
const PM_WHEN_OUT_OF_QUEST_SCROLLS = true;

const NOTIFY_ON_QUEST_END = true;

const AUTO_CAST_SKILLS = true;

const AUTO_PAUSE_RESUME_DAMAGE = false;
const MAX_PLAYER_DAMAGE = 20;
const MAX_PARTY_DAMAGE = 5;

const AUTO_ALLOCATE_STAT_POINTS = false;
const STAT_TO_ALLOCATE = "int"; // str, int, con, per

const AUTO_PURCHASE_GEMS = true; // subscribers only

const AUTO_PURCHASE_ARMOIRES = false;
const RESERVE_GOLD = 50000;

const AUTO_SELL_EGGS = false;
const RESERVE_EGGS = 999;

const AUTO_SELL_HATCHING_POTIONS = false;
const RESERVE_HATCHING_POTIONS = 999;

const AUTO_SELL_FOOD = false;
const RESERVE_FOOD = 999;

const AUTO_HATCH_FEED_PETS = true;
const ONLY_USE_DROP_FOOD = true;

const HIDE_PARTY_NOTIFICATIONS = false;
const HIDE_ALL_GUILD_NOTIFICATIONS = false;
const HIDE_NOTIFICATIONS_FROM_SPECIFIC_GUILDS = [ // only used if HIDE_ALL_GUILD_NOTIFICATIONS is false
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // enter a guild ID between the quotes to hide notifications from that guild
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" // repeat for as many guilds as you want
```

**Comment by bumbleshoot** [comment]
Hi @blackcatsnow, I just checked your script and your webhooks. You have two different deployments running at the same time, and you have webhooks pointing to both deployments. This should not happen if the instructions were followed correctly. It appears you may have created a new deployment at some point, rather than creating a new version of the deployment? Please carefully follow [these instructions](https://github.com/bumbleshoot/automate-habitica#updating-the-script) to update your script, that should fix the issue (and will update it to the newest version, so you get all the new features/bug fixes!)
