### ISSUE TITLE
Automate Habitica error since last 24 h

### ISSUE THREAD

**Issue by Falzart** [bumbleshoot/automate-habitica#35]
**What is the bug?**
Every 10 minutes, the script send me an error message. The message is like this:
TypeError: Cannot read properties of undefined (reading 'Milk')
     at hatchFeedPets (automations/hatchFeedPets:128:73)
     at processQueue (global:413:11)
     at onTrigger (global:31:5)
     at __GS_INTERNAL_top_function_call__.gs:1:8

**Additional context**
I don't do anything on the script, also not on my Habitica character. It just suddenly pop up 

**How often does this happen?**
Every 10 minutes. 

**Script version**
V 0.29.36

**Script settings**
default setting

**Comment by bumbleshoot** [comment]
Thanks for the bug report @Falzart! Multiple people reported the same problem around the same time you did. Because this wasn't an issue previously, and now several people are reporting it at once, I suspect it has something to do with an update Habitica made. I will look into it as soon as I can - a bit swamped with life stuff right now. In the meantime, your best course of action would be to disable Auto Hatch/Feed Pets by following [these instructions](https://github.com/bumbleshoot/automate-habitica#changing-the-settings).

**Comment by zdraco** [comment]
happened to me as well!

**Comment by bumbleshoot** [comment]
Hi @Falzart, can you please try enabling Auto Hatch/Feed Pets again (using [these instructions](https://github.com/bumbleshoot/automate-habitica#changing-the-settings)) and let me know if you get any more of these error messages? Thanks!

**Comment by Falzart** [comment]
Because of the continuous error messages, I moved the script to brand new Google account on June 30th. Just logged in to said new account (because I read this reply) and found the error messages persisted only until July 1st.

Thank you. I will let you know if anything else goes wrong. 😃

**Comment by bumbleshoot** [comment]
Great! I did not make any changes to the code. I investigated the error message and the code and determined that it was probably an issue on Habitica's end. I tested my own copy of the script and didn't get the error message, so I figured the problem had been fixed. Thanks for confirming that!
